spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sijang?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: sijang
    password: sijang
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      repositories:
        enabled: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ""
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me

mybatis:
  mapper-locations: classpath:/s3/mergewhat/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.s3.mergewhat: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 3600000
